export const galleryImages = [
  { src: "/images/team/partners-namaste.jpg", alt: "Yogacharya Manish and Yogini Pooja standing in namaste", width: 1400, height: 1050 },
  { src: "/images/studio/mass-session.jpg", alt: "Hundreds of practitioners on mats at a Yogic Company session", width: 1400, height: 900 },
  { src: "/images/team/yogacharya-manish.jpg", alt: "Yogacharya Manish seated in meditation outdoors", width: 1200, height: 1500 },
  { src: "/images/studio/group-session-hall.jpg", alt: "A large indoor group yoga session", width: 1400, height: 900 },
  { src: "/images/team/yogini-pooja.jpg", alt: "Yogini Pooja holding a seated yoga posture", width: 1200, height: 1500 },
  { src: "/images/studio/group-session-outdoor.jpg", alt: "A mass yoga session held in an open hall", width: 1400, height: 900 },
  { src: "/images/studio/studio-practice.jpg", alt: "A studio class holding a forward-facing posture", width: 1400, height: 900 },
  { src: "/images/team/manish-and-pooja.jpg", alt: "Yogacharya Manish and Yogini Pooja seated in meditation together", width: 1400, height: 900 },
  { src: "/images/studio/alternate-nostril-breathing.jpg", alt: "A young woman practising alternate nostril breathing", width: 1200, height: 1400 },
  { src: "/images/team/manish-with-teacher.jpg", alt: "Yogacharya Manish practising alongside his teacher", width: 1200, height: 800 },
  { src: "/images/about/rejuvenation-banner.jpg", alt: "Rejuvenation — unlocking the calm within", width: 1366, height: 768 },
  { src: "/images/about/philosophy-field.jpg", alt: "A lone figure standing in a vast field of sunflowers", width: 1400, height: 900 },
  { src: "/images/about/white-paper-print.jpg", alt: "Printed Yogic Company white paper showing lungs formed from trees", width: 540, height: 753 },
  { src: "/images/about/breathe-core.jpg", alt: "A softly glowing circle with the word breathe at its centre", width: 1200, height: 1200 },
  { src: "/images/journal/sunflower.jpg", alt: "A single sunflower against an open sky", width: 736, height: 1285 },
];
